all:
	make -C ./Level_1/
	make -C ./Level_2/
	make -C ./Level_3/

clean:
	make -C ./Level_1/ clean
	make -C ./Level_2/ clean
	make -C ./Level_3/ clean

ac:
	make -C ./Level_1/ clean all
	make -C ./Level_2/ clean all
	make -C ./Level_3/ clean all
