all:
	make -C ./Level_1/
	make -C ./Level_2/
	make -C ./Level_3/
	make -C ./Level_4/
	make -C ./InitTests/
	make -C ./LoopTests/

clean:
	make -C ./Level_1/ clean
	make -C ./Level_2/ clean
	make -C ./Level_3/ clean
	make -C ./Level_4/ clean
	make -C ./InitTests/ clean
	make -C ./LoopTests/ clean

ac:
	make -C ./Level_1/ clean all
	make -C ./Level_2/ clean all
	make -C ./Level_3/ clean all
	make -C ./Level_4/ clean all
	make -C ./InitTests/ clean all
	make -C ./LoopTests/ clean all
