# CppUTest Makefile

#--- Inputs ----#
COMPONENT_NAME = roboCooler_Int
include ../settings/Makefile

SRC_DIRS = \
	../../integration\
	../mockFiles\
	../mockFiles/stdlib\

TEST_SRC_DIRS += \
	./mockFiles\

TEST_SRC_FILES +=\

INCLUDE_DIRS +=\
  .\
  ./mockFiles\
  ../../integration\
  ../../src/timer\
  $(CPPUTEST_HOME)/include\

include $(CPPUTEST_HOME)/build/MakefileWorker.mk



